services:
  postgres:
    image: postgres:17
    container_name: xplain_pg
    environment:
      POSTGRES_USER: hmwaio
      POSTGRES_PASSWORD: Hmwaio123
      POSTGRES_DB: mydb
    ports:
      - "5433:5432"   # host:container
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    name: xplain_backend_pg_data